name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.41.1-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb
      - name: Run Playwright tests with Xvfb
        run: xvfb-run dotnet test
      - run: dotnet build
      - name: Run your tests
        run: dotnet test
        env:
          HOME: /root